### ISSUE TITLE
Syntax Error line 663

### ISSUE THREAD

**Issue by markscherz** [simonhmartin/twisst#14]
I cannot run twisst, either on my linux server or locally on my mac, due to a syntax error:

```
  File "twisst.py", line 663
    print(".", end="", file=sys.stderr, flush=True)
                  ^
SyntaxError: invalid syntax
```

Any ideas on what's going wrong?

Cheers,
Mark

**Comment by markscherz** [comment]
I think this is because I was missing dependencies.

**Comment by skitchen19** [comment]
I encountered the same error. Were you able to identify the dependency that was missing?

**Comment by simonhmartin** [comment]
No this looks like a python version error. You need to use Python 3. I never saw the original issue as it was closed on the same day, but the original answer about dependencies is incorrect.
