### ISSUE TITLE
Weight calculation fails mid-analysis

### ISSUE THREAD

**Issue by TonyKess** [simonhmartin/twisst#15]
Hello,

I've been using twisst for a few projects recently, but keep running into this error on my most recent set of analyses after switching to phyml for constructing trees:

`.Traceback (most recent call last):
  File "/home/tkess/twisst/twisst.py", line 637, in <module>
    simplify=not args.skip_simplify, abortCutoff=args.abortCutoff, verbose=args.verbose, taxonNames=taxonNames)
  File "/home/tkess/twisst/twisst.py", line 359, in weightTree
    rootLeafChains = makeRootLeafChainDict(tree, collapseDict=taxonDict if simplify else None, preserveDists=getDists, treeFormat=treeFormat)
  File "/home/tkess/twisst/twisst.py", line 300, in makeRootLeafChainDict
    chains = getChainsToLeaves(tree, collapseDict=collapseDict, preserveDists=preserveDists)
  File "/home/tkess/twisst/twisst.py", line 158, in getChainsToLeaves
    childrenChains = [getChainsToLeaves(child, collapseDict, preserveDists) for child in children]
  File "/home/tkess/twisst/twisst.py", line 158, in <listcomp>
File "/home/tkess/twisst/twisst.py", line 154, in getChainsToLeaves
    chain = NodeChain([node], dists = [] if preserveDists else None)
  File "/home/tkess/twisst/twisst.py", line 62, in __init__
    super(NodeChain, self).__init__(nodeList)
RecursionError: maximum recursion depth exceeded while calling a Python object
`

I get this error after getting weights for ~1000 windows, so something is going wrong during the weights calculation mid-analysis. Has anyone seen something like this before?

Tony

**Comment by simonhmartin** [comment]
Hi Tony,
I haven't encountered this before. The error involves some code I introduced recently to speed up the weights computation. It involves recursively descending into the tree from the root until the tips are reached. Python has an inbuilt limit for how much recursion is allowed, to prevent infinite loops and memory overflow. This can be increased, but I'd be surprised if this is really being reached, unless the tree is very large. Do you have a large number of samples? If so, then perhaps try subsampling to see if this is indeed the problem.

**Comment by TonyKess** [comment]
Hi Simon,

Downsampling from ~600 genomes down to 100 seems to have fixed this issue and sped up analysis significantly. Thanks for your help,  

Tony
