### ISSUE TITLE
diploid species tree IDs

### ISSUE THREAD

**Issue by shiyi-pan** [simonhmartin/twisst#16]
hi， I uesd unphased VCF file of a dipoild soybean  to build tree file by 'phyml_sliding_windows.py'. but the result has a '_A' and '_B' suffix . is that correct ? if I want a result without the '_A' and '_B' suffix ,What should I do?

**Comment by simonhmartin** [comment]
Yes, that script will automatically convert diploid sequences into two haploid sequences, even if the data is unphased. I assume what you want is to represent each diploid individual as a single tip in the tree?
This is possible in principle, but it has some problems.

1. The theoretical problem
If you have a population genomic dataset, the two haplotypes from each individual are not likely to be each other's closest relative at all parts of the genome, so forcing them into a single tip is somewhat meaningless.
2. The practical problem
Phylogeny inference tools need a single sequence for each individual. Some, like RAxML, allow heterozygous genotypes to be represented by IUPAC ambiguity characters, but others like Phyml, will just ignore these sites for tree inference. This means that more heterozygous individuals will have less information used to infer their position in the tree.

If you still want to go ahead with this, you need to convert the geno file into 'diplo' format, which you can do with the my `filterGenotypes.py` script, setting `--outputGenoFormat diplo`. You can then infer trees as you have done. If the Phyml script fails with the ambiguity codes, try the raxml one.

**Comment by shiyi-pan** [comment]
thank you for your reply. Considering that the species is self pollinated soybean, I will try the filterGenotypes.py script.
