### ISSUE TITLE
About the numbers in the weights file 

### ISSUE THREAD

**Issue by mxg1987** [simonhmartin/twisst#17]
Hi, When I used Twisst to compute topology weights, I got a result file like this.
#topo1 (outgroup,((AQ,LO),GY));
#topo2 (outgroup,((AQ,GY),LO));
#topo3 (outgroup,(AQ,(LO,GY)));
topo1	topo2	topo3
topo1	topo2	topo3
0	1	0
1	0	0
1	0	0
1	0	0
0	1	0
0	1	0
0	1	0
0	1	0
1	0	0
0	1	0

The weights file only contains number 0 or 1 for each topo.
Is this an abnormal situation? 
Why I didn't get the absolute counts for each  topo?

**Comment by simonhmartin** [comment]
Hi,
This would happen if you only have a single sequence representing each group. Is that the case? The values computed by Twisst reflect the proportion of all possible sample combinations that support a given topology. If there is just a single representative of each group (i.e. 4 sequences total), then there is only a single combination of individuals, and each topology is either present or absent (1 or 0).

**Comment by mxg1987** [comment]
Sorry, I made a mistake. I have mutiple samples for each group. But I didn't separate them by commas (,).
Now the problem has been solved. Thanks for your reply.

**Comment by simonhmartin** [comment]
No worries.
