### ISSUE TITLE
plotting specific regions within chromosomes

### ISSUE THREAD

**Issue by sibelletorres** [simonhmartin/twisst#19]
Hi Simon, do you have a suggestion how I can specify in twisst.plot plotting the weights for specific regions within a scaffold/chromosome? For example, If I want to plot the region within 1000-50,000 bp of chromosome/scaffold 3, how could I specify it? I tried subset.twisst.by.regions but only succeeded subsetting by chromosome/scaffold. Thank you!

**Comment by simonhmartin** [comment]
Hi,
Sure - this is possible. The `plot.twisst` function is just a 'wrapper' of other functions, but you can run those others individually to have more control. In particular, the `plot.weights` function makes a plot for a single region and takes an `xlim` argument to specify start and end. You need to specify a bit more information for the `plot.weights` function. You can see an example in the `example_plot.R` script, under the headings "individual plots: raw weights" and "individual plots: smoothed weights".
