### ISSUE TITLE
Problem with twisst output 

### ISSUE THREAD

**Issue by cbrock2** [simonhmartin/twisst#2]
Hi Simon,

I'm a Postdoc working in Katie Wagner's lab and II have been running some preliminary twisst analyses on some trees (from sliding window raxml analyses). Everything runs fine, but when I look at the 'weights' output file I do not see weights or counts for each topology, only the topologies themselves followed by a series of rows that begin by listing the topology names and then shifts to nan. 

Here is an excerpt:

#topo1 (kivu9 | (((((sweya | kivu3) | kivu5) | kivu6) | kivu7) | kivu8));
-- | -- | -- | -- | -- | -- | --
#topo2 (kivu9 | (((((sweya | kivu3) | kivu5) | kivu6) | kivu8) | kivu7));
#topo3 (kivu9 | ((((sweya | kivu3) | kivu5) | kivu6) | (kivu7 | kivu8)));
#topo4 (kivu9 | (((((sweya | kivu3) | kivu5) | kivu7) | kivu6) | kivu8));
#topo5 (kivu9 | (((((sweya | kivu3) | kivu5) | kivu7) | kivu8) | kivu6));
#topo6 (kivu9 | ((((sweya | kivu3) | kivu5) | kivu7) | (kivu6 | kivu8)));
#topo7 (kivu9 | (((((sweya | kivu3) | kivu5) | kivu8) | kivu6) | kivu7));
#topo8 (kivu9 | (((((sweya | kivu3) | kivu5) | kivu8) | kivu7) | kivu6));
#topo9 (kivu9 | ((((sweya | kivu3) | kivu5) | kivu8) | (kivu6 | kivu7)));
.
.
.
.
topo1	topo2	topo3	topo4	topo5	topo6 ...
nan nan nan nan nan ...

I was wondering if you had any advice or thoughts about what could be going wrong. I have 74 individual samples broken into 8 taxa. I'll keep playing around with this, but I thought I would write to ask if you had any thoughts. 

Thanks for the very useful scripts and thanks for your time.

Best

Chad

**Comment by cbrock2** [comment]
Hi Simon,

I believe I have traced back the problem to the sliding window analyses, where the outputs are 'NAs.' I think I can sort out the issue, but I will post again if I have any more problems. Sorry for wasting your time.

Thanks,

Chad

**Comment by cbrock2** [comment]
Hi Simon,

I have traced the issue to the output from the sliding raxml analyses. The tree file is all NA. It looks like (from the code) this is either due to not meeting some stated min number of sites or individuals, or from a failure to locate/open the tree file from the raxml analyses. Since I haven't used the other flags for minimums, my guess is it's the latter. 

I have tried to trouble-shoot by using the 'test' option, but it won't output the raxml command line. Additionally, trying to output the log file from raxml fails as well (it doesn't show up in the directory). I also removed the 'silent' command from the raxml function, but again did not glean any additional information. 

I'm gonna keep working on it, but if there is any suggestions you have to get the trees to properly output I would greatly appreciate it.

My data is phased and I am using the following command to run the sliding windows analyses:

python raxml_sliding.py -g output.geno.gz --prefix Chr1snps.raxml.w50 -w 50 --windType sites --model GTRCAT --outgroup CEW16064s2,CEW16080s2,CEW16088s2,CEW16103s2 --test --genoFormat phased --log /gscratch/cbrock2/sr.log --verbose --raxml /apps/user/intel-16/raxml-8.2.8/bin/raxmlHPC

Thanks again for your time,

Chad

**Comment by cbrock2** [comment]
Hi Simon,

I figured out the issue. My version of RaxML needed the "-T" designation, and did not recognize the "--silent" command. I adjusted the python script accordingly and now everything works fine.

Thanks again for the helpful code.

Best,

Chad

**Comment by simonhmartin** [comment]
Hi Chad,
Sorry for the delay, but I'm glad you solved the issue. I have noted the
issue with the raxml script.
Best,
Simon

**Comment by cbrock2** [comment]
Hi Simon,

No problem. Thanks again for the python tools.

Best,

Chad
