### ISSUE TITLE
Importance/impact of using phased data

### ISSUE THREAD

**Issue by a-lud** [simonhmartin/twisst#21]
Hi Simon,

The publication for twisst recommends that diploid reseq data should be phased if possible. I'm just wondering if is valid to use unphased data with the software, and if it is viable, what impact unphased data will have on the results from twisst. 

Thanks for the help

Alastair

**Comment by simonhmartin** [comment]
Hi,
Sorry for the delay!

I strongly recommend using phased data, and I believe that even badly phased data would be better than making a tree where you represent a diploid pair of sequences as if it is one haploid sequence. The reason this is problematic is that the two haplotypes in a random outbred individual will have independent ancestries, and therefore represent two separate tips in the genealogy. By forcing them together, you will be inferring a false genealogy, where each tip will probably occupy an intermediate position between the two sequences it represents. The resulting weightings will therefore not be accurate, but it is difficult to predict in what way they will be affected.

However, there are some circumstances where forcing two tips into one is less of a problem. If your groups are largely monophyletic in any part of the genome, then the weightings at any part of the genome will tend to be either 1 or 0, and the use of a false tree will not really change that. Even if a lot of the genome does represent incompletely sorted trees, but you are only interested in the regions where weightings approach 1 or 0 (e.g. regions where there have been introgressed sweeps), then you can probably trust these extreme weightings even when using a false tree with pseudo-haploid sequences.

Hope this helps!
Simon

**Comment by a-lud** [comment]
That was extremely helpful! Thanks for the detailed response. 

Cheers
Alastair

**Comment by simonhmartin** [comment]
No problem!
