### ISSUE TITLE
Error getting twisst.py to run

### ISSUE THREAD

**Issue by skitchen19** [simonhmartin/twisst#22]
I encountered the same error. Were you able to identify the dependency that was missing?

```
File "./twisst/twisst.py", line 666
    print(".", end="", file=sys.stderr, flush=True)
                  ^
SyntaxError: invalid syntax
```
Installed versions:
ete3 v3.1.2
numpy v1.15.4
python v2.7.15

Thanks!

_Originally posted by @skitchen19 in https://github.com/simonhmartin/twisst/issues/14#issuecomment-777918352_

**Comment by simonhmartin** [comment]
As stated in the other answer, using Python 3+ should fix it.
