### ISSUE TITLE
error while using phyml_sliding_windows.py "No module named 'genomics'

### ISSUE THREAD

**Issue by Jungal10** [simonhmartin/twisst#24]
I was able to use all the other tools to come from bams to trees. although when I reach the step to use phyml, it always fails with a missing module:

```
phyml_sliding_windows.py", line 19, in <module>
    import genomics
ModuleNotFoundError: No module named 'genomics'
```

I have phyml installed, I tried with the environment where the ETE toolkit is installed as well and I always go back to this missing module.

Any help to solve the issue?

Thanks

P.S. I tried the same with Raxml and I had the same problem (I have raxml installed as well)

**Comment by sandyplus** [comment]
You have to add the path to your script
```

#add parent directory to path in case genomics.py is there instead of on the path
#sys.path.insert(1, os.path.realpath(os.path.pardir))
sys.path.insert(1, "/home/path/to/genomics_general-master")

import genomics
```

**Comment by simonhmartin** [comment]
> You have to add the path to your script
Yes this is one solution. Another less elegant solution is to copy the genomics.py script to the same directory.
