### ISSUE TITLE
AssertionError: Please specify 

### ISSUE THREAD

**Issue by hyyuu** [simonhmartin/twisst#42]
Hello,

Thank you for your program! 
I encountered an error when I ran TWISST in a 10-taxon data set.
```
assert 4 <= len(branches) <= 8, "Please specify between 4 and 8 unique taxon names."
AssertionError: Please specify between 4 and 8 unique taxon names.

```
However, I have assigned all taxon into groups.  
`-g R Lasent -g Cep Liginc -g Hex Pedetontus_sp_ -g Cope Calsin -g B Trilon -g Out Rsan -g Oli Parsp_ -g The Ppol -g Per Porpru -g De Lvan`
Could you please recommend how to solve this problem ? I have attached the tree file for your reference. 
Thank you very much for your kind help !
[405-set2-10t-all-root.txt](https://github.com/simonhmartin/twisst/files/12004987/405-set2-10t-all-root.txt)

Best,
Alex

**Comment by simonhmartin** [comment]
Hi, in Twisst the term taxon is equivalent to group. Running with 10 groups would result in an almost infinite number of topologies. I recommend starting your first analysis with 4 or 5 groups, to keep the interpretation manageable.
