### ISSUE TITLE
AttributeError: 'module' object has no attribute 'weightTreeSimp'

### ISSUE THREAD

**Issue by YanCheer** [simonhmartin/twisst#47]
Hi! Dear Martin,
When I ran twisst analysis with `run_twisst_parallel.py`, I accidentally got an error reporting that 

> AttributeError: 'module' object has no attribute 'weightTreeSimp'

How can I address this issue?

Best Regards,
Chen Yan

**Comment by simonhmartin** [comment]
Sorry for the slow response. The parallel version no longer works, but the single thread version is fast enough that this shouldn't be a serious problem.
