### ISSUE TITLE
Topology affected by order of group definition arguments

### ISSUE THREAD

**Issue by vlkofly** [simonhmartin/twisst#8]
Dear Simon,
I have encountered a strange behaviour of your program. Identical set of input trees is giving me different twisst results, and it has something to do with order of group definition arguments. 
For example while using following command:  
`python $twisst --threads $nt -t ${base}.trees.gz -w ${base}.weights.csv.gz --outputTopos ${base}.topologies.trees $gr --method complete`
where
`gr="-g I I_364_A,I_364_B,I_370_A,I_370_B,I_380_A,I_380_B -g D D_001_A,D_001_B,D_002_A,D_002_B,D_013_A,D_013_B -g W W_001_A,W_001_B,W_009_A,W_009_B,W_025_A,W_025_B -g M M_182_A,M_182_B,M_192_A,M_192_B,M_208_A,M_208_B -g P P_001_A,P_001_B,P_016_A,P_016_B,P_017_A,P_017_B -g S S_001_A,S_001_B,S_005_A,S_005_B,S_140_A,S_140_B -g C C_254_A,C_254_B,C_256_A,C_256_B,C_270_A,C_270_B -g F F_272_A,F_272_B,F_276_A,F_276_B,F_280_A,F_280_B "`
These are the best topos:
#topo1 (F,((((((I,D),W),M),P),S),C));
#topo2 (F,((((((I,D),W),M),P),C),S));
#topo3 (F,(((((I,D),W),M),P),(S,C)));
#topo4 (F,((((((I,D),W),M),S),P),C));

And if I change gr:
`#gr="-g C C_254_A,C_254_B,C_256_A,C_256_B,C_270_A,C_270_B -g F F_272_A,F_272_B,F_276_A,F_276_B,F_280_A,F_280_B -g I I_364_A,I_364_B,I_370_A,I_370_B,I_380_A,I_380_B -g M M_182_A,M_182_B,M_192_A,M_192_B,M_208_A,M_208_B -g P P_001_A,P_001_B,P_016_A,P_016_B,P_017_A,P_017_B -g S S_001_A,S_001_B,S_005_A,S_005_B,S_140_A,S_140_B -g W W_001_A,W_001_B,W_009_A,W_009_B,W_025_A,W_025_B"`
then 
#topo1 (W,(((((C,F),I),M),P),S));
#topo2 (W,(((((C,F),I),M),S),P));
#topo3 (W,((((C,F),I),M),(P,S)));
#topo4 (W,(((((C,F),I),P),M),S));

The last taxon in the line of -g arguments is always taken as an outgroup and the topology mirrors the order as well. The topologies from twisst do not make much sense biologically while input trees seems to be OK. Am I doing something wrong, or is it an expected behaviour, or is it a bug?
Thanks in advance,

Jakub

PS: in the second example I missed one taxon, but even if I do not miss it the strange behaviour remains.

**Comment by simonhmartin** [comment]
Hi Jakub,
This may or may not be a bug, depending on what is happening to the weightings values.
The weightings should not be affected by rooting, however, I wrote the code to output rooted trees because I assumed that's what people would want.

The order in which the trees are listed (#topo1 etc) is arbitrary, and determined by the input order only, so topo1 will not be the same in your two runs.

The way to test if there is a real bug is to identify which topology in the second run matches topo1 in the first run and then compare their weightings.

Hope this makes sense?
-Simon

**Comment by vlkofly** [comment]
Hi Simon,
1. It is confusing that order of -g arguments defines what group will be used as outgroup. It should be mentioned in the readme.

2. Order of -g arguments affect weightings:

![twisst_bug](https://user-images.githubusercontent.com/24706763/58881745-17658600-86db-11e9-8d03-53a31934bba5.png)

At least from what is seen on this average weightings plot. The figures are from the example described above.

What would you suggest to do?

**Comment by simonhmartin** [comment]
Hmm that really is worrying. Would you be willing to send me a sample of your input file (just the first few trees should be fine) so I can try debug this?

**Comment by vlkofly** [comment]
Here is how I run it: https://github.com/vlkofly/popgenome-metacentrum/blob/master/run_twisst.sh
And first 200 trees. 
[Mmel_Chr9.phased.trees.example.gz](https://github.com/simonhmartin/twisst/files/3252769/Mmel_Chr9.phased.trees.example.gz)

**Comment by simonhmartin** [comment]
This is odd - I get very different results from you.

I defined four ways of grouping, either with 7 taxa or 8:

```
gr1="-g C C_254_A,C_254_B,C_256_A,C_256_B,C_270_A,C_270_B -g F F_272_A,F_272_B,F_276_A,F_276_B,F_280_A,F_280_B -g I I_364_A,I_364_B,I_370_A,I_370_B,I_380_A,I_380_B -g M M_182_A,M_182_B,M_192_A,M_192_B,M_208_A,M_208_B -g P P_001_A,P_001_B,P_016_A,P_016_B,P_017_A,P_017_B -g S S_001_A,S_001_B,S_005_A,S_005_B,S_140_A,S_140_B -g W W_001_A,W_001_B,W_009_A,W_009_B,W_025_A,W_025_B"

gr2="-g C C_254_A,C_254_B,C_256_A,C_256_B,C_270_A,C_270_B -g W W_001_A,W_001_B,W_009_A,W_009_B,W_025_A,W_025_B -g F F_272_A,F_272_B,F_276_A,F_276_B,F_280_A,F_280_B -g I I_364_A,I_364_B,I_370_A,I_370_B,I_380_A,I_380_B -g M M_182_A,M_182_B,M_192_A,M_192_B,M_208_A,M_208_B -g P P_001_A,P_001_B,P_016_A,P_016_B,P_017_A,P_017_B -g S S_001_A,S_001_B,S_005_A,S_005_B,S_140_A,S_140_B"


gr3="-g I I_364_A,I_364_B,I_370_A,I_370_B,I_380_A,I_380_B -g D D_001_A,D_001_B,D_002_A,D_002_B,D_013_A,D_013_B -g W W_001_A,W_001_B,W_009_A,W_009_B,W_025_A,W_025_B -g M M_182_A,M_182_B,M_192_A,M_192_B,M_208_A,M_208_B -g P P_001_A,P_001_B,P_016_A,P_016_B,P_017_A,P_017_B -g S S_001_A,S_001_B,S_005_A,S_005_B,S_140_A,S_140_B -g C C_254_A,C_254_B,C_256_A,C_256_B,C_270_A,C_270_B -g F F_272_A,F_272_B,F_276_A,F_276_B,F_280_A,F_280_B"

gr4="-g I I_364_A,I_364_B,I_370_A,I_370_B,I_380_A,I_380_B -g F F_272_A,F_272_B,F_276_A,F_276_B,F_280_A,F_280_B -g D D_001_A,D_001_B,D_002_A,D_002_B,D_013_A,D_013_B -g W W_001_A,W_001_B,W_009_A,W_009_B,W_025_A,W_025_B -g M M_182_A,M_182_B,M_192_A,M_192_B,M_208_A,M_208_B -g P P_001_A,P_001_B,P_016_A,P_016_B,P_017_A,P_017_B -g S S_001_A,S_001_B,S_005_A,S_005_B,S_140_A,S_140_B -g C C_254_A,C_254_B,C_256_A,C_256_B,C_270_A,C_270_B"
```

I then ran twisst for each of these:

```
python run_twisst_parallel.py --threads 6 $gr1 --method complete -w Mmel.1.weights -t Mmel_Chr9.phased.trees.example.gz

python run_twisst_parallel.py --threads 6 $gr2 --method complete -w Mmel.2.weights -t Mmel_Chr9.phased.trees.example.gz

python run_twisst_parallel.py --threads 6 $gr3 --method complete -w Mmel.3.weights -t Mmel_Chr9.phased.trees.example.gz

python run_twisst_parallel.py --threads 6 $gr4 --method complete -w Mmel.4.weights -t Mmel_Chr9.phased.trees.example.gz
```

I added an option to my plot_twisst.R code to allow plotting a summary for just the best N topologies. I just pushed up this version. I used this in R to plot the top 10 topologies for each:

```
source("plot_twisst.R")

twisst_data <- import.twisst(weights_files="Mmel.1.weights")
plot.twisst.summary(twisst_data, lwd=3, cex=0.7, only_best=10, cols=rep("black",11000), y_scale=0.1)

twisst_data <- import.twisst(weights_files="Mmel.2.weights")
plot.twisst.summary(twisst_data, lwd=3, cex=0.7, only_best=10, cols=rep("black",11000), y_scale=0.1)

twisst_data <- import.twisst(weights_files="Mmel.3.weights")
plot.twisst.summary(twisst_data, lwd=3, cex=0.7, only_best=10, cols=rep("black",11000), y_scale=0.1)

twisst_data <- import.twisst(weights_files="Mmel.4.weights")
plot.twisst.summary(twisst_data, lwd=3, cex=0.7, only_best=10, cols=rep("black",11000), y_scale=0.1)
```

The result changes when adding the 8th taxon, but not in the same way that you found. And there is no difference with different group orders.

Not sure why your example image looks so different. I can't make out the taxa used, but I'm assuming they are the same is in my tests?

**Comment by vlkofly** [comment]
Hello Simon,
the problem was in my script, I have overlooked the fact that the order of topologies is arbitrary when subsetting the weights.  So the new version of plot.twisst.summary plotting only the best 10 topos solved my problem. Thanks. Im closing this issue.
